name: ci

on: [push]

jobs:

  build_in_docker:

    runs-on: self-hosted #ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: docker build -t docker_alm .
    - name: Run tests in docker
      run: mkdir coverage-html && docker run --rm -v $(pwd)/coverage-html:/app/build/coverage-html docker_alm:latest
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: coverage-html      