name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y lcov
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
    - name: build
      run: cmake --build build
    - name: run
      run: cd build/; ctest -V --output-on-failure
    - name: Generate coverage report
      run: |
        cd build;
        lcov --directory . --capture --output-file coverage.info;
        lcov --extract coverage.info '*/src/*' '*/inc/*' --output-file coverage.info
        lcov --list coverage.info;
        genhtml coverage.info --output-directory coverage-html;
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: build/coverage-html