name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y gcovr
    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Debug -DCODE_COVERAGE=ON
    - name: build
      run: cmake --build build
    - name: run
      run: cd build/; ctest -V --output-on-failure
    - name: Generate coverage report
      run: |
        cd build; mkdir -p coverage-html;
        gcovr --root .. \
          --exclude '../test' --exclude '_deps' \
          --html --html-details -o coverage-html/index.html \
          --print-summary \
          --branches \
          --fail-under-line=100 \
          --fail-under-function=100 \
          --fail-under-branch=90
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-coverage-report
        path: build/coverage-html