name: ci

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: cmake
      run: mkdir build; cd build; cmake ..
    - name: make
      run: cd build/; make
    - name: run
      run: cd build/; ctest -V
    - name: coverage
      run: cd build/; VERSION="1.14"; mkdir Iconv; cd Iconv; wget "https://github.com/linux-test-project/lcov/releases/download/v1.14/lcov-$VERSION.tar.gz"; tar -xzf "lcov-$VERSION.tar.gz"; cd "lcov-$VERSION"; sudo make install; lcov --directory . --capture --output-file coverage.info --ignore-errors mismatch; lcov --remove coverage.info '/usr/*' '*/test/*' '*/gtest/*' '*/googletest/*' --output-file coverage_filtered.info; genhtml coverage_filtered.info --output-directory coverage_report